import { GoogleGenAI } from "@google/genai";
import { consumeApiCall } from "./daily-limit";
import type { CompetitorCommonAnalysis, CompetitorItem } from "./types";

const STOP = new Set(["그리고","하지만","그래서","있는","없는","입니다","있습니다","합니다","하게","저희","오늘","정말","너무","사진","촬영","웨딩","본식","스냅","신랑","신부","예식","결혼","작가","메인","위해","통해","대한","때문","이번","같은","하는","했던","되는","에서","으로","에게","까지","부터","보다","정도","부분","모습","진행","시간"]);
function topWords(text:string,mainKeyword:string,limit=8){const kp=new Set(mainKeyword.split(/\s+/).filter(Boolean));const words=text.match(/[가-힣A-Za-z0-9]{2,}/g)||[];const c=new Map<string,number>();for(const raw of words){const w=raw.trim();if(STOP.has(w)||kp.has(w)||/^\d+$/.test(w))continue;c.set(w,(c.get(w)||0)+1);}return [...c.entries()].filter(([,n])=>n>=2).sort((a,b)=>b[1]-a[1]).slice(0,limit).map(([w])=>w);}
function fallback(items:CompetitorItem[],keyword:string):CompetitorCommonAnalysis{const all=items.filter(x=>x.crawled&&x.rawText);const buckets=all.map(x=>topWords(x.rawText||"",keyword,12));const f=new Map<string,number>();buckets.flat().forEach(k=>f.set(k,(f.get(k)||0)+1));const commonKeywords=[...f.entries()].sort((a,b)=>b[1]-a[1]).slice(0,8).map(([k])=>k);const avgImages=all.length?Math.round(all.reduce((s,x)=>s+(x.imageCount||0),0)/all.length):25;const min=Math.max(12,Math.round(avgImages*.85)),max=Math.max(min+6,Math.round(avgImages*1.15));return{commonKeywords,commonFeatures:["식장/홀명 중심 제목","사진 중심으로 예식 흐름을 보여줌","신부대기실·입장·본식·행진 순서의 구성"],photoCommonFeatures:["본문 사이에 사진을 연속 배치하는 비중이 높음","홀 전경과 인물 장면을 섞어 레퍼런스를 제공"],strengths:["실제 촬영 결과물을 많이 보여줘 상담 레퍼런스로 활용하기 좋음"],gaps:["메인작가 관점의 조명·동선·촬영 포인트 설명은 더 강화할 여지가 있음"],takeaways:["식장/홀명 중심의 검색 의도에 맞춘 제목과 구성","예식 순서대로 사진을 충분히 보여주는 방식"],differentiators:["사진마다 작가 시선의 짧은 설명 추가","홀 투어에서 알기 어려운 촬영 동선·조명·사진 결과 팁 강화"],overallReview:"상위 글들은 웨딩홀 검색 의도에 맞는 실제 사진 레퍼런스를 충분히 제공하는 경향이 있습니다. 우리 글은 여기에 메인작가의 현장 팁을 더해 상담 자료로서의 가치를 높이는 방향이 좋습니다.",contentStrategy:"사진 레퍼런스를 충분히 보여주되 각 구간마다 메인작가가 직접 확인한 조명·동선·촬영 포인트를 짧고 구체적으로 덧붙입니다. 고객이 링크 하나만 받아도 해당 식장과 홀의 사진 분위기와 촬영 특징을 파악할 수 있게 구성합니다.",suggestedKeywords:commonKeywords.slice(0,5).map(k=>({keyword:k,min:1,max:3,reason:"상위 글에서 반복적으로 등장"})),photoTotalMin:min,photoTotalMax:max,photoPlan:[{section:"홀/공간 소개",min:3,max:5,note:"홀 전경·버진로드·조명 분위기"},{section:"신부대기실",min:4,max:7,note:"대기실 전경과 인물 레퍼런스"},{section:"식전·입장",min:4,max:6,note:"동선과 입장 직전 분위기"},{section:"본식 주요 순간",min:8,max:12,note:"입장·서약·축가·부모님·행진"},{section:"마무리/원판",min:3,max:5,note:"플라워샤워·원판·엔딩"}]};}
function sleep(ms:number){return new Promise(r=>setTimeout(r,ms));}
function geminiModels(){return Array.from(new Set([process.env.GEMINI_MODEL||"gemini-3.7-flash",...(process.env.GEMINI_FALLBACK_MODELS||"gemini-3.6-flash,gemini-3.5-flash-lite").split(",").map(x=>x.trim()).filter(Boolean)]));}
async function geminiGenerate(ai:GoogleGenAI,contents:any){let last:any;for(const model of geminiModels()){for(let a=0;a<3;a++){try{return await ai.models.generateContent({model,contents});}catch(e:any){last=e;const m=String(e?.message||e);if(!/503|429|UNAVAILABLE|RESOURCE_EXHAUSTED/i.test(m))throw e;if(a<2)await sleep(1000*Math.pow(2,a));}}}throw last||new Error("Gemini API 호출 실패");}
function extractJson(text:string){const fenced=text.match(/```(?:json)?\s*([\s\S]*?)```/i)?.[1];const candidate=fenced||text.slice(text.indexOf("{"),text.lastIndexOf("}")+1);return JSON.parse(candidate);}
async function imagePart(url:string){try{const r=await fetch(url,{headers:{"User-Agent":"Mozilla/5.0","Referer":"https://m.blog.naver.com/"},signal:AbortSignal.timeout(8000)});if(!r.ok)return null;const type=r.headers.get("content-type")||"image/jpeg";if(!type.startsWith("image/"))return null;const buf=Buffer.from(await r.arrayBuffer());if(buf.length>4_000_000)return null;return {inlineData:{mimeType:type,data:buf.toString("base64")}};}catch{return null;}}

export async function analyzeCompetitorsWithGemini(items:CompetitorItem[],keyword:string):Promise<CompetitorCommonAnalysis>{
 const crawled=items.filter(x=>x.crawled&&x.rawText).slice(0,7); if(!crawled.length||!process.env.GEMINI_API_KEY)return fallback(items,keyword);
 try{
  await consumeApiCall("gemini"); const ai=new GoogleGenAI({apiKey:process.env.GEMINI_API_KEY});
  const payload=crawled.map((x,i)=>({rank:i+1,title:x.title,charCount:x.charCount,imageCount:x.imageCount,headingCount:x.headingCount,paragraphCount:x.paragraphCount,keywordCount:x.keywordCount,confidence:x.confidence,text:(x.rawText||"").slice(0,14000)}));
  const parts:any[]=[{text:`당신은 네이버 웨딩스냅 블로그 벤치마킹 분석가다. 검색 키워드: ${keyword}\n아래는 사용자가 실제 네이버 검색에서 확인한 상위 글 최대 7개의 본문 및 구조 데이터다.\n${JSON.stringify(payload)}\n\n각 글을 사람이 직접 읽어본 것처럼 최대한 구체적으로 분석하되, 제공된 텍스트/이미지에서 확인되지 않는 내용은 추측하지 마라. 이어지는 이미지에는 [글 N 대표이미지] 라벨이 붙는다. 이미지가 없는 글은 사진 스타일을 단정하지 마라.\n\n목표 블로그 운영자는 실제 본식을 촬영하는 웨딩스냅 메인작가다. 목적은 ① 상담 시 식장·홀 레퍼런스 사진을 인스타그램보다 많이 보여주고 링크 하나로 제공, ② 홀 투어에서 얻기 어려운 조명·동선·촬영 포인트를 메인작가가 제공하는 것이다.\n\n각 글별로: 자주 쓰는 키워드, 콘텐츠 특징, 사진 구성 특징, 작가 관점 정보의 정도, SEO/구조 특징, 총평을 작성하라. 그 뒤 7개 공통점, 사진 공통점, 강점, 빈틈, 우리가 가져올 것, 우리가 다르게 할 것, 추가 키워드 3~7개, 추천 사진 수와 구간별 배치를 도출하라. 사진 수가 상위노출을 보장한다고 단정하지 않는다.\n\n반드시 JSON만 출력:\n{"items":[{"rank":1,"frequentKeywords":["..."],"contentFeatures":["..."],"photoFeatures":["..."],"authorPerspective":"...","seoStructure":["..."],"review":"...","confidence":90}],"commonKeywords":["..."],"commonFeatures":["..."],"photoCommonFeatures":["..."],"strengths":["..."],"gaps":["..."],"takeaways":["..."],"differentiators":["..."],"overallReview":"...","contentStrategy":"...","suggestedKeywords":[{"keyword":"...","min":1,"max":3,"reason":"..."}],"photoTotalMin":20,"photoTotalMax":35,"photoPlan":[{"section":"홀/공간 소개","min":3,"max":5,"note":"..."}]}`}];
  for(let i=0;i<crawled.length;i++){const urls=(crawled[i].imageUrls||[]).slice(0,2);for(const url of urls){const p=await imagePart(url);if(p){parts.push({text:`[글 ${i+1} 대표이미지]`});parts.push(p);}}}
  const response=await geminiGenerate(ai,[{role:"user",parts}]); const parsed=extractJson(response.text||"");
  for(const row of parsed.items||[]){const item=crawled[(Number(row.rank)||1)-1];if(item){item.frequentKeywords=Array.isArray(row.frequentKeywords)?row.frequentKeywords.slice(0,10):[];item.contentFeatures=Array.isArray(row.contentFeatures)?row.contentFeatures.slice(0,6):[];item.photoFeatures=Array.isArray(row.photoFeatures)?row.photoFeatures.slice(0,5):[];item.authorPerspective=String(row.authorPerspective||"");item.seoStructure=Array.isArray(row.seoStructure)?row.seoStructure.slice(0,5):[];item.review=String(row.review||"");item.confidence=Math.max(0,Math.min(100,Number(row.confidence)||item.confidence||60));}}
  const fb=fallback(items,keyword);return{commonKeywords:Array.isArray(parsed.commonKeywords)?parsed.commonKeywords.slice(0,12):fb.commonKeywords,commonFeatures:Array.isArray(parsed.commonFeatures)?parsed.commonFeatures.slice(0,8):fb.commonFeatures,photoCommonFeatures:Array.isArray(parsed.photoCommonFeatures)?parsed.photoCommonFeatures.slice(0,8):fb.photoCommonFeatures,strengths:Array.isArray(parsed.strengths)?parsed.strengths.slice(0,6):fb.strengths,gaps:Array.isArray(parsed.gaps)?parsed.gaps.slice(0,6):fb.gaps,takeaways:Array.isArray(parsed.takeaways)?parsed.takeaways.slice(0,6):fb.takeaways,differentiators:Array.isArray(parsed.differentiators)?parsed.differentiators.slice(0,6):fb.differentiators,overallReview:String(parsed.overallReview||fb.overallReview),contentStrategy:String(parsed.contentStrategy||fb.contentStrategy),suggestedKeywords:Array.isArray(parsed.suggestedKeywords)?parsed.suggestedKeywords.slice(0,7).map((x:any)=>({keyword:String(x.keyword||"").trim(),min:Math.max(1,Number(x.min)||1),max:Math.max(1,Number(x.max)||3),reason:String(x.reason||"")})).filter((x:any)=>x.keyword):fb.suggestedKeywords,photoTotalMin:Math.max(5,Number(parsed.photoTotalMin)||fb.photoTotalMin),photoTotalMax:Math.max(10,Number(parsed.photoTotalMax)||fb.photoTotalMax),photoPlan:Array.isArray(parsed.photoPlan)?parsed.photoPlan.slice(0,8).map((x:any)=>({section:String(x.section||"구간"),min:Math.max(1,Number(x.min)||1),max:Math.max(1,Number(x.max)||3),note:String(x.note||"")})):fb.photoPlan};
 }catch(e){console.error("[COMPETITOR AI ANALYSIS FALLBACK]",e);return fallback(items,keyword);}
}
